# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Node.js image
FROM node:18-alpine

# Create and change to the app directory
WORKDIR /usr/src/app

# Install server dependencies
COPY package.json /usr/src/app/
COPY package-lock.json /usr/src/app/
RUN npm install --omit=dev

# Copy the server code
COPY dist /usr/src/app/dist

# Set the environment variable for WordPress site configuration
# This is an example path; ensure the actual path is correctly set when running the container
ENV WP_SITES_PATH=/path/to/wp-sites.json

# Expose the port the app runs on (example port, change as needed)
EXPOSE 3000

# Command to run the app
CMD ["node", "dist/index.js"]